apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
  meshConfig:
    accessLogFile: "/dev/stdout"
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    enableTracing: true
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    meshMTLS:
      cipherSuites:
        - ECDHE-RSA-AES256-GCM-SHA384
