apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: hochacha/echo-server
        ports:
        - containerPort: 12345
      - name: bpf
        image: hochacha/bpf-container:sleep
        imagePullPolicy: Always
        securityContext:
          privileged: true