apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyMetadata:
        PILOT_LOG_LEVEL: "debug"
    meshMTLS:
      cipherSuites:
      - AES256-GCM-SHA384

